### ISSUE TITLE
Get the tool to check if assets exist before activating, creating the idlist, and clipping?

### ISSUE THREAD

**Issue by kendonB** [samapriya/Clip-Ship-Planet-CLI#6]
Currently, the tool only checks if the asset exists at the download stage. Is it feasible to get the tool to also check if assets exist before activating, creating the idlist, and clipping? This could save a huge amount of time when going back to fill in gaps of failed downloads.

**Comment by samapriya** [comment]
**Please note that the Clip API has been [deprecated](https://developers.planet.com/changelog/).** The tool already checks that while creating the IDList, however, the issue is when you are using a derivative of an item and asset combination. For example, the IDlist created from PSScene4Band analytic and analytic_sr are similar but analytic_sr asset types may not exist. As such though desirable, this is not an efficient feature to integrate completely but something I might be able to revisit. Also failed downloads are not because of images not being available but also that clipping may not be completed.
